#!/bin/bash

set -eu
   
d=`pwd`
echo "== Repository: $d"

git annex info
git show git-annex:remote.log | grep s3-PU

function showkey() {
    key="$1"
    git ls-tree -r git-annex | grep $key | while read _ _ _ afile; do 
        echo "-- $afile:"
        git show git-annex:$afile;
    done
}

for file in "$@"; do
    # file=$(head -n1 <(git-annex find --not --in here --fast | grep '\.nii.gz'))
    key=$(readlink $file | xargs basename)

    git annex whereis $file

    echo "---- Key before get"
    showkey "$key"

    echo "---- Let's fetch the beast"
    git annex get "$file"

    echo "---- Key after get"
    showkey "$key"
    echo
done
